#!/bin/bash
# 快速参考指南

echo "=========================================="
echo "自动导航 - 快速参考"
echo "=========================================="
echo ""
echo "📍 获取坐标工具:"
echo "   ros2 run pb2025_nav_bringup get_coordinates.py"
echo ""
echo "   然后在 RViz 中使用 'Nav2 Goal' 或 '2D Pose Estimate' 点击地图"
echo ""
echo "🔄 控制云台自旋:"
echo "   停止自旋:"
echo "   ros2 topic pub --once /red_standard_robot1/cmd_spin std_msgs/msg/Float32 '{data: 0.0}'"
echo ""
echo "   恢复自旋:"
echo "   ros2 topic pub --once /red_standard_robot1/cmd_spin std_msgs/msg/Float32 '{data: 3.14}'"
echo ""
echo "🚀 启动自动导航:"
echo "   ros2 launch pb2025_nav_bringup auto_navigation_launch.py"
echo ""
echo "📝 配置文件位置:"
echo "   导航参数: src/pb2025_sentry_nav/pb2025_nav_bringup/config/simulation/nav2_params.yaml"
echo "   自动导航: src/pb2025_sentry_nav/pb2025_nav_bringup/scripts/auto_navigation.py"
echo ""
echo "=========================================="
